
//num is the number of dice being rolled, d is highest value of the die being rolled (4 for d4, 6, for d6, etc.)
function dice(num,d) {
    roll = 0;
    for (i = 0; i < num; i++) {
        roll += randomDieRoll(d,1);
    }
    return roll;
}

function randomDieRoll(max,min) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

let activity = [
    'celebrating',
    'chasing ',
    'constructing',
    'defecating',
    'dying/wounded',
    'fleeing from ',
    'hallucinating',
    'hunting/foraging',
    'in combat with ',
    'journey/pilgrimage',
    'lost/exploring',
    'marking territory',
    'mating/courting',
    'negotiating with ',
    'patrolling/guarding',
    'resting/camping',
    'ritual/magic',
    'sleeping',
    'trapped/imprisoned',
    'washing',
]

let animalEncounter = [
    `Bat, Giant* (${dice(1,10)})`,
    `Bear* (${dice(1,4)})`,
    `Boar* (${dice(1,6)})`,
    `Burrowing Beetle* (${dice(2,4)})`,
    `Carrion Worm* (${dice(1,3)})`,
    `Centipede, Giant* (${dice(1,8)})`,
    `False Unicorn* (${dice(3,4)})`,
    `Fire Beetle, Giant* (${dice(2,6)})`,
    `Fly, Giant* (${dice(2,6)})`,
    `Insect Swarm (${dice(1,3)})`,
    `Rapacious Beetle* (${dice(2,4)})`,
    `Rat, Giant* (${dice(3,6)})`,
    `Red Deer* (${dice(3,10)})`,
    `Shaggy Mammoth* (${dice(2,8)})`,
    `Snake—Adder* (${dice(1,8)})`,
    `Stirge* (${dice(2,6)})`,
    `Toad, Giant* (${dice(1,4)})`,
    `Weasel, Giant* (${dice(1,6)})`,
    `Red Deer* (${dice(3,10)})`,
    `Wolf* (${dice(3,6)})`,
    `Yegril* (${dice(3,8)})`,
]

let humanEncounter = [
    `Adventuring Party`,
    `Cleric† (${dice(1,20)})`,
    `Crier‡ (${dice(1,6)})`,
    `Drune—Cottager (${dice(1,4)})`,
    `Fighter† (${dice(2,6)})`,
    `Fortune-Teller‡ (${dice(1,3)})`,
    `Friar† (${dice(1,6)})`,
    `Hunter† (${dice(3,6)})`,
    `Knight† (${dice(2,6)})`,
    `Lost Soul‡ (${dice(1,4)})`,
    `Magician† (${dice(1,4)})`,
    `Merchant‡ (${dice(1,20)})`,
    `Pedlar‡ (${dice(1,4)})`,
    `Pedlar‡ (${dice(1,4)})`,
    `Pilgrim‡ (${dice(4,8)})`,
    `Priest‡ (${dice(1,6)})`,
    `Thief (Bandit)† (${dice(3,10)})`,
    `Thief (Bandit)† (${dice(3,10)})`,
    `Villager‡ (${dice(2,10)})`,
    `Witch (${dice(1,6)})`,
]

let monsterEncounter = [
    `Ant, Giant* (${dice(3,4)})`,
    `Centaur—Bestial (1)`,
    `Cockatrice (${dice(1,4)})`,
    `Ghoul (${dice(2,4)})`,
    `Griffon* (${dice(2,8)})`,
    `Headless Rider (${dice(1,4)})`,
    `Mogglewomp (1)`,
    `Mugwudge (${dice(1,4)})`,
    `Ogre (${dice(1,6)})`,
    `Owlbear* (${dice(1,4)})`,
    `Root Thing (${dice(1,4)})`,
    `Snail, Giant—Mutant (${dice(1,3)})`,
    `Spinning Spider, Giant* (${dice(1,3)})`,
    `Stirge* (${dice(2,6)})`,
    `Treowere (${dice(1,8)})`,
    `Werewolf (${dice(1,6)})`,
    `Wolf, Dire* (${dice(2,4)})`,
    `Wyrm—Black Bile (1)`,
    `Wyrm—Blood (1)`,
    `Yickerwill (${dice(1,6)})`,
]

let sentientEncounter = [
    `Barrowbogey (${dice(2,6)})`,
    `Breggle—Shorthorn (${dice(3,10)})`,
    `Crookhorn (${dice(3,10)})`,
    `Deorling—Stag (${dice(1,6)})`,
    `Elf—Courtier or Knight (${dice(1,4)})`,
    `Elf—Wanderer (${dice(1,6)})`,
    `Goblin (${dice(2,6)})`,
    `Grimalkin (${dice(1,4)})`,
    `Mossling (${dice(2,8)})`,
    `Nutcap (${dice(2,6)})`,
    `Redcap (${dice(2,6)})`,
    `Scarecrow (${dice(1,4)})`,
    `Scrabey (${dice(1,6)})`,
    `Shape-Stealer (${dice(1,6)})`,
    `Sprite (${dice(3,6)})`,
    `Talking Animal (${dice(1,4)})`,
    `Treowere (${dice(1,8)})`,
    `Troll (${dice(1,3)})`,
    `Wodewose (${dice(1,6)})`,
    `Woodgrue (${dice(3,6)})`,

]

let aldwealdEncounter = [
    `Antler Wraith (${dice(2,4)})`,
    `Breggle—Shorthorn (${dice(3,10)})`,
    `Centaur—Sylvan (${dice(2,6)})`,
    `Deorling—Doe (${dice(4,4)})`,
    `Elf—Knight (${dice(1,4)})`,
    `Elf—Wanderer (${dice(1,6)})`,
    `Fairy Horse (1)`,
    `Gelatinous Hulk (${dice(1,4)})`,
    `Gloam (1)`,
    `Goblin (${dice(2,6)})`,
    `Grimalkin (${dice(1,4)})`,
    `Pedlar‡ (${dice(1,4)})`,
    `Redcap (${dice(2,6)})`,
    `Snail, Giant—Psionic (1)`,
    `Sprite (${dice(3,6)})`,
    `Thief (Bandit)† (${dice(3,10)})`,
    `Unicorn—Blessed (${dice(1,6)})`,
    `Wild Hunt (see p355)`,
    `Witch (${dice(1,6)})`,
    `Woodgrue (${dice(3,6)})`,
]

let aquaticEncounters = [
    `Adventuring Party`,
    `Angler‡ (${dice(2,4)})`,
    `Boggin (${dice(1,6)})`,
    `Catfish, Giant* (${dice(1,2)})`,
    `Crab, Giant* (${dice(1,6)})`,
    `Fly, Giant* (${dice(2,6)})`,
    `Insect Swarm* (${dice(1,3)})`,
    `Kelpie (1)`,
    `Killer Bee* (${dice(2,6)})`,
    `Leech, Giant* (${dice(1,4)})`,
    `Madtom (${dice(1,12)})`,
    `Merchant‡ (${dice(1,20)})`,
    `Merfaun (${dice(2,6)})`,
    `Pedlar‡ (${dice(1,4)})`,
    `Pike, Giant* (${dice(1,4)})`,
    `Stirge* (${dice(2,6)})`,
    `Thief (Pirate)† (${dice(3,10)})`,
    `Toad, Giant* (${dice(1,4)})`,
    `Water Termite, Giant* (${dice(1,3)})`,
    `Wyrm—Phlegm (1)`,
]

let dwelmfurghEncounter = [
    `Antler Wraith (${dice(2,4)})`,
    `Basilisk (${dice(1,6)})`,
    `Brambling (${dice(1,4)})`,
    `Centipede, Giant* (${dice(1,8)})`,
    `Crookhorn (${dice(3,10)})`,
    `Drune—Audrune (1)`,
    `Drune—Braithmaid (${dice(1,4)})`,
    `Drune—Cottager (${dice(1,4)})`,
    `Drune—Cottager (${dice(2,6)})`,
    `Drune—Drunewife (1)`,
    `Lost Soul‡ (${dice(1,4)})`,
    `Shadow (${dice(1,8)})`,
    `Skeleton (${dice(3,6)})`,
    `Spinning Spider, Giant* (${dice(1,3)})`,
    `Sprite (${dice(3,6)})`,
    `Thief (Bandit)† (${dice(3,10)})`,
    `Wicker Giant (1)`,
    `Wight (${dice(1,6)})`,
    `Witch (${dice(1,6)})`,
    `Wyrm—Yellow Bile (1)`,
]

let feverMarshEncounter = [
    `Bat, Vampire* (${dice(1,10)})`,
    `Black Tentacles (${dice(1,4)})`,
    `Bog Salamander (${dice(1,3)})`,
    `Centaur—Bestial (1)`,
    `Crookhorn (${dice(3,10)})`,
    `Fly, Giant* (${dice(2,6)})`,
    `Galosher (${dice(2,6)})`,
    `Gelatinous Hulk (${dice(1,4)})`,
    `Harridan (${dice(1,3)})`,
    `Insect Swarm* (${dice(1,3)})`,
    `Jack-o’-Lantern (${dice(1,8)})`,
    `Leech, Giant* (${dice(1,4)})`,
    `Madtom (${dice(1,12)})`,
    `Marsh Lantern (${dice(1,12)})`,
    `Mugwudge (${dice(1,4)})`,
    `Redcap (${dice(2,6)})`,
    `Shadow (${dice(1,8)})`,
    `Toad, Giant* (${dice(1,4)})`,
    `Troll (${dice(1,3)})`,
    `Wyrm—Phlegm (1)`,
]

let hagsAddleEncounter = [
    `Banshee (1)`,
    `Bat, Giant* (${dice(1,10)})`,
    `Black Tentacles (${dice(1,4)})`,
    `Bog Corpse (${dice(2,4)})`,
    `Bog Salamander (${dice(1,3)})`,
    `Boggin (${dice(1,6)})`,
    `Galosher (${dice(2,6)})`,
    `Ghoul (${dice(2,4)})`,
    `Gloam (1)`,
    `Leech, Giant* (${dice(1,4)})`,
    `Marsh Lantern (${dice(1,12)})`,
    `Mugwudge (${dice(1,4)})`,
    `Shadow (${dice(1,8)})`,
    `Swamp Sloth* (${dice(1,6)})`,
    `Swamp Spider, Giant* (${dice(1,3)})`,
    `The Hag (see p82)`,
    `Toad, Giant* (${dice(1,4)})`,
    `Troll (${dice(1,3)})`,
    `Unicorn—Corrupt (${dice(1,6)})`,
    `Wronguncle (1)`,
]

let highWoldEncounter = [
    `Barrowbogey (${dice(2,6)})`,
    `Breggle—Longhorn (${dice(2,4)})`,
    `Breggle—Shorthorn (${dice(3,10)})`,
    `Breggle—Shorthorn (${dice(3,10)})`,
    `Crier‡ (${dice(1,6)})`,
    `Devil Goat (${dice(1,4)})`,
    `Drune—Braithmaid (${dice(1,4)})`,
    `Drune—Cottager (${dice(1,4)})`,
    `Elf—Knight (${dice(1,4)})`,
    `Goblin (${dice(2,6)})`,
    `Grimalkin (${dice(1,4)})`,
    `Knight† (${dice(2,6)})`,
    `Merchant‡ (${dice(1,20)})`,
    `Pedlar‡ (${dice(1,4)})`,
    `Priest‡ (${dice(1,6)})`,
    `Scrabey (${dice(1,6)})`,
    `Thief (Bandit)† (${dice(3,10)})`,
    `Witch (${dice(1,6)})`,
    `Witch Owl (${dice(1,6)})`,
    `Woodgrue (${dice(3,6)})`,
]

let mulchgroveEncounter = [
    `Bat, Vampire* (${dice(1,10)})`,
    `Bog Corpse (${dice(2,4)})`,
    `Bog Salamander (${dice(1,3)})`,
    `Brainconk (${dice(1,8)})`,
    `Gelatinous Hulk (${dice(1,4)})`,
    `Jack-o’-Lantern (${dice(1,8)})`,
    `Mossling (${dice(2,8)})`,
    `Mossling (${dice(2,8)})`,
    `Mossling (${dice(2,8)})`,
    `Mossling (${dice(4,8)})`,
    `Mould Oracle (${dice(1,3)})`,
    `Ochre Slime-Hulk (1)`,
    `Ochre Slime-Hulk (1)`,
    `Ochre Slime-Hulk (1)`,
    `Onyx Blob (1)`,
    `Pook Morel (${dice(2,10)})`,
    `Pook Morel (${dice(2,10)})`,
    `Redslob (${dice(1,4)})`,
    `Redslob (${dice(1,4)})`,
    `Wronguncle (1)`,
]

let nagwoodEncounter = [
    `Atanuwë (see p45)`,
    `Bat, Vampire* (${dice(1,10)})`,
    `Bog Corpse (${dice(2,4)})`,
    `Centaur—Bestial (1)`,
    `Crookhorn (${dice(3,10)})`,
    `Crookhorn (${dice(3,10)})`,
    `Crookhorn (${dice(6,10)})`,
    `Harpy (${dice(2,4)})`,
    `Harridan (${dice(1,3)})`,
    `Manticore (${dice(1,4)})`,
    `Ochre Slime-Hulk (1)`,
    `Ogre (${dice(1,6)})`,
    `Ogre (${dice(1,6)})`,
    `Owlbear* (${dice(1,4)})`,
    `Snail, Giant—Mutant (${dice(1,3)})`,
    `Spinning Spider, Giant (${dice(1,4)})`,
    `Treowere (Chaotic) (${dice(1,8)})`,
    `Unicorn—Corrupt (${dice(1,6)})`,
    `Wolf, Dire* (${dice(2,4)})`,
    `Wyrm—Black Bile (1)`,
]

let northernScratchEncounter = [
    `Banshee (1)`,
    `Bat, Vampire* (${dice(1,10)})`,
    `Black Tentacles (${dice(1,4)})`,
    `Bog Corpse (${dice(2,4)})`,
    `Bog Salamander (${dice(1,3)})`,
    `Deorling—Stag (${dice(1,6)})`,
    `Fomorian (${dice(1,3)})`,
    `Galosher (${dice(2,6)})`,
    `Gloam (1)`,
    `Harridan (${dice(1,3)})`,
    `Leech, Giant* (${dice(1,4)})`,
    `Madtom (${dice(1,12)})`,
    `Marsh Lantern (${dice(1,12)})`,
    `Mugwudge (${dice(1,4)})`,
    `Redcap (${dice(2,6)})`,
    `Scarecrow (${dice(1,4)})`,
    `Shadow (${dice(1,8)})`,
    `Spectre (${dice(1,4)})`,
    `Wight (${dice(1,6)})`,
    `Witch Owl (${dice(1,6)})`,
]

let tablesDownsEncounter = [
    `Banshee (1)})`,
    `Crookhorn (${dice(3,10)})`,
    `Deorling—Doe (${dice(4,4)})`,
    `Drune—Cottager (${dice(1,4)})`,
    `Elf—Wanderer (${dice(1,6)})`,
    `Fly, Giant* (${dice(2,6)})`,
    `Ghoul (${dice(2,4)})`,
    `Gloam (1)`,
    `Harpy (${dice(2,4)})`,
    `Headless Rider (${dice(1,4)})`,
    `Lost Soul‡ (${dice(1,4)})`,
    `Peryton (${dice(2,4)})`,
    `Peryton (${dice(2,4)})`,
    `Shadow (${dice(1,8)})`,
    `Shape-Stealer (${dice(1,6)})`,
    `Skeleton (${dice(3,6)})`,
    `Spectre (${dice(1,4)})`,
    `Wight (${dice(1,6)})`,
    `Witch (${dice(1,6)})`,
    `Woodgrue (${dice(3,6)})`,
]

let tithelandsEncounter = [
    `Breggle—Shorthorn (${dice(3,10)})`,
    `Cleric† (${dice(1,20)})`,
    `Elf—Wanderer (${dice(1,6)})`,
    `Fighter† (${dice(2,6)})`,
    `Friar† (${dice(1,6)})`,
    `Gloam (1)`,
    `Goblin (${dice(2,6)})`,
    `Griffon* (${dice(2,8)})`,
    `Grimalkin (${dice(1,4)})`,
    `Killer Bee* (${dice(2,6)})`,
    `Knight† (${dice(2,6)})`,
    `Merchant‡ (${dice(1,20)})`,
    `Mossling (${dice(2,8)})`,
    `Pilgrim‡ (${dice(4,8)})`,
    `Pook Morel (${dice(2,10)})`,
    `Scrabey (${dice(1,6)})`,
    `Sprite (${dice(3,6)})`,
    `Villager‡ (${dice(2,10)})`,
    `Witch (${dice(1,6)})`,
    `Woodgrue (${dice(3,6)})`,
]

let wiseBeastEncounters = [
    `Cobbin (${dice(1,4)})`,
    `Cobbin (${dice(1,4)})`,
    `Cobbin (${dice(1,4)})`,
    `Cobbin (${dice(3,8)})`,
    `Crookhorn (${dice(3,10)})`,
    `Crookhorn (${dice(3,10)})`,
    `Crookhorn (${dice(3,10)})`,
    `Deorling—Stag (${dice(1,6)})`,
    `Goblin (${dice(2,6)})`,
    `Grimalkin (${dice(1,4)})`,
    `Lost Soul‡ (${dice(1,4)})`,
    `Mossling (${dice(2,8)})`,
    `Ochre Slime-Hulk (1)`,
    `Ogre (${dice(1,6)})`,
    `Owlbear* (${dice(1,4)})`,
    `Redslob (${dice(1,4)})`,
    `Sprite (${dice(3,6)})`,
    `Troll (${dice(1,3)})`,
    `Wodewose (${dice(1,6)})`,
    `Woodgrue (${dice(3,6)})`,
]
